name: GitHub Pages Deploy

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17.3.0

      - name: Install dependencies
        # -> Yarn equivalent to 'npm ci'
        run: yarn install --frozen-lockfile

      - name: Static Site Generation (SSG)
        # -> Production build + static file export using Next.js
        run: yarn build:html

      - name: Commit to 'gh-pages' branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./out
          github_token: ${{ secrets.GITHUB_TOKEN }}
